### ISSUE TITLE
replace `lodash.isequal` & `lodash.clonedeep` for smaller bundle size & performance

### ISSUE THREAD

**Issue by jrson83** [inertiajs-revamped/inertia#15]
### Packages

inertiajs-revamped/preact, inertiajs-revamped/react, inertiajs-revamped/vue

### Is your feature request related to an issue?

No

### Describe the feature

I like to replace `lodash.isequal` & `lodash.clonedeep` with smaller & faster packages.

Here is my suggestion:

`lodash.isequal`

https://www.npmjs.com/package/fast-equals
https://github.com/planttheidea/fast-equals

`lodash.clonedeep`

https://www.npmjs.com/package/@visulima/deep-clone
https://github.com/visulima/visulima/blob/main/packages/deep-clone

Any suggestions welcome.

**Comment by Julien-R44** [comment]
For cloneDeep i would suggest `structuredClone` that is native: https://caniuse.com/?search=structuredClone 

not supported absolutely everywhere but we can probably include a polyfill if we really want to support more browsers

**Comment by jrson83** [comment]
After checking this great [article](https://www.builder.io/blog/structured-clone), I replaced lodash.clonedeep with structured-clone. I did not test in depth, only with some templates, but if all fails we just revert.

**Comment by jrson83** [comment]
In addition I replaced lodash.isequal with fast-equals for now.

Any suggestion related smaller/faster replacements are still welcome.
